### ISSUE TITLE
Can not override deep-forest.html

### ISSUE THREAD

**Issue by miratcan** [tokitouq/drf-dark-shade#3]
I've overridden the template show my branding and put it to templates/drf_dark_shade/deep-forest.html but it's being ignored. Can you share an example config to override branding?

**Comment by tokitouq** [comment]
Hi @miratcan!
I've fixed the issue, now you can override the template however you want.

example config: https://github.com/tokitouq/drf-dark-shade/tree/main/examples
doc: https://github.com/tokitouq/drf-dark-shade?tab=readme-ov-file#override-templates

lemme know if you face any other issues.
have a nice day :heart:
